### ISSUE TITLE
Make authors and tags clickable

### ISSUE THREAD

**Issue by romainricard** [signalstickers/signalstickers#153]
As suggested by a fellow user, it would be nice if, in the `/pack/` view, we could click on author or tags to search for them on the website.

**Comment by darkobits** [comment]
This might wind up producing a lot of noise in search results, because each term searches across all fields. For example, if we had a pack named **Foo** and a user clicked on an author named **Foo**, that pack would appear in the results even though it was not what the user was looking for.

One way to make searching more robust would be to implement a query syntax. To search for all packs by author `Foo` with titles that contain the string `bar`:

```
author:Foo bar
```

Reddit [uses a syntax like this](https://www.reddit.com/wiki/search) for their search feature. I don't think ours would need to be anywhere near that complex, but something along those lines could make search a lot more customizable, and let us easily implement the sort of highly-focused links we're talking about.

**Comment by romainricard** [comment]
This would lead to a massive refactor of the search engine. We could also include search for packs that are `original` in the process.

**Comment by romainricard** [comment]
I actually already developed the bare feature of this Issue. [We can merge it](https://github.com/signalstickers/signalstickers/pull/156), and create another Issue to improve the search engine. What do you think?
