### ISSUE TITLE
stickers.yml

### ISSUE THREAD

**Issue by CrayonPeChan** [signalstickers/signalstickers#595]
https://signal.art/addstickers/#pack_id=90185bd47d961ae03d6aab9391ca27ff&pack_key=5e5f7f8fe162c40507431c0befce419a1e376334aec6a7702c7901c453a2f1ef

**Comment by CrayonPeChan** [comment]
Hi,I would like to upload my signal stickers,thank you

**Comment by darkobits** [comment]
To get your sticker pack added to the Signal Stickers directory, please follow the instructions on our [Contribute](https://signalstickers.com/contribute) page.

Rather than opening a Pull Request, you can just share the YAML generated by the form in this thread, and we'll get the pack added for you.

Thanks!

**Comment by romainricard** [comment]
I've added it. @CrayonPeChan please use the form next time! :smiley:
